# @format

version: "3"

services:
  db:
    image: mysql:5.7
    container_name: task-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "6033:3306"
    volumes:
      - task-dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: task-pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  task-dbdata:
